# Copyright 2026
# SPDX-License-Identifier: Apache-2.0
"""Proof-of-Concept artifact generation — inert, human-run only.

For each confirmed finding we write ONE flat file ``pocs/<F-id>__<slug>.md``. The
harness NEVER executes anything. A top-level ``pocs/README.md`` indexes them all with
a review-before-running banner.

The **Reproduction sketch** is the important part: it always states the HTTP method,
endpoint, required headers (e.g. the session cookie for an auth flow), body, and a
ready-to-run ``curl`` so an analyst can test the finding directly. It is resolved
(best-effort) from the deterministic ``sample_request`` (built by ``endpoints.py``,
which now walks the call graph up to the enclosing route), then an optional
LLM-provided recipe, then a concrete per-category fallback.
"""
from __future__ import annotations

import shlex
from pathlib import Path

from .findings import Finding

_INDEX_BANNER = """\
# Proof-of-Concept Artifacts

> ⚠️ **REVIEW BEFORE RUNNING.** These PoCs were generated by an LLM and are
> provided INERT. The scanner never executed them. Adapt endpoints/credentials to
> your environment and run only in an isolated environment you control.

| ID | Severity | Location | Title |
|----|----------|----------|-------|
"""

_HOW_TO_RUN = """\
# PoC — {title}

> ⚠️ REVIEW BEFORE RUNNING. Generated by an LLM; the scanner never executed it.
> Run only against a target you own, in an isolated environment.

- **Finding ID:** {fid}
- **Severity:** {severity}  |  **CWE:** {cwe}  |  **Reachable:** {reachable}
- **Location:** `{file_rel}:{line_start}-{line_end}`

## What it demonstrates
{description}

## Reproduction sketch
{poc_sketch}

## Expected vs vulnerable behavior
- Expected (patched): the input is rejected / handled safely.
- Vulnerable: {vulnerable_behavior}
"""


def generate_pocs(findings: list[Finding], out_dir: Path, *,
                  poc_sketches: dict[str, str] | None = None) -> int:
    """Write inert PoC files (one flat .md per finding). Returns count written."""
    poc_root = Path(out_dir) / "pocs"
    poc_root.mkdir(parents=True, exist_ok=True)
    sketches = poc_sketches or {}

    index_rows: list[str] = []
    written = 0
    for f in findings:
        if f.status not in ("confirmed", "new") or f.reachable == "unreachable":
            continue
        fid = f.short_id()  # stable display ID — matches the report's finding id
        fname = f"{fid}__{f.slug()}.md"
        # Precedence: the DETERMINISTIC sample request (a real route + curl parsed
        # from the source) always wins. An LLM sketch is only consulted when route
        # resolution failed, and is sanitized first. The per-category fallback is last.
        #
        # The LLM sketch used to win outright, which let a model replace a working,
        # verified curl with a fully `#`-commented "sketch" a reviewer can't run.
        sketch = (_sketch_from_sample_request(f)
                  or _sanitize_sketch(sketches.get(f.fingerprint()))
                  or _default_sketch(f))

        (poc_root / fname).write_text(_HOW_TO_RUN.format(
            fid=fid, title=f.title or f.category, severity=f.severity,
            cwe=f.cwe or "n/a", reachable=f.reachable, file_rel=f.file_rel,
            line_start=f.line_start, line_end=f.line_end,
            description=f.description or "", poc_sketch=sketch,
            vulnerable_behavior=f.description or "the unsafe path is taken",
        ), encoding="utf-8")
        index_rows.append(
            f"| [{fid}]({fname}) | {f.severity} | `{f.file_rel}:{f.line_start}` "
            f"| {f.title or f.category} |")
        written += 1

    (poc_root / "README.md").write_text(_INDEX_BANNER + "\n".join(index_rows) + "\n",
                                        encoding="utf-8")
    return written


def _sketch_from_sample_request(f: Finding) -> str | None:
    """Render the deterministic malicious sample request as a complete, UNCOMMENTED
    reproduction sketch (method/endpoint/headers/body/curl). Returns None when the
    finding has no ``sample_request`` (couldn't resolve an HTTP handler)."""
    sr = getattr(f, "sample_request", None)
    if not sr or not sr.get("curl"):
        return None
    method = sr.get("method", "GET")
    path = sr.get("path", "")
    note = sr.get("payload_note", "")
    cite = sr.get("citation", "")
    headers = sr.get("headers") or []
    body = sr.get("body")
    params = sr.get("params") or []

    lines = [
        f"- **Method:** {method}",
        f"- **Endpoint:** `{path}`",
    ]
    if headers:
        lines.append("- **Headers:**")
        lines += [f"    - `{h}`" for h in headers]
    if body:
        lines.append(f"- **Body:** `{body}`")
    if params:
        pretty = ", ".join(f"{p.get('name')} ({p.get('in')})" for p in params)
        lines.append(f"- **Parameters:** {pretty}")
    if note:
        lines.append(f"- **Payload:** {note}")
    if cite:
        lines.append(f"- **Handler:** `{cite}`")
    # Provenance so a red teamer knows how trustworthy the route is.
    deriv = sr.get("derivation", "")
    _prov = {
        "derived": "_Route resolved deterministically from the code._",
        "inferred": "_Route resolved from code; parameter best-effort._",
        "llm-verified": "_Route resolved by LLM and confirmed against the source code._",
    }.get(deriv)
    lines += [
        "",
        "Run against a target you own (set `<BASE_URL>`):",
        "",
        "```bash",
        sr["curl"],
        "```",
    ]
    if _prov:
        lines += ["", _prov]
    return "\n".join(lines)


def _sanitize_sketch(text: str | None) -> str | None:
    """Vet an LLM-supplied reproduction sketch, or return None to fall back.

    Rejects a sketch that is entirely commented out or prose-only. Models sometimes
    "helpfully" comment out every command for safety, which produces a PoC with no
    runnable step — worse than the deterministic per-category fallback, because it
    looks complete. Fenced code blocks are kept verbatim; only bare lines are judged.
    """
    if not text or not text.strip():
        return None

    runnable = False
    in_fence = False
    for raw in text.splitlines():
        line = raw.strip()
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if not line:
            continue
        if in_fence:
            # Inside a code fence, a non-comment line counts as runnable.
            if not line.startswith("#"):
                runnable = True
        elif line.startswith(("curl ", "http ", "$ ", "GET ", "POST ", "PUT ",
                              "DELETE ", "PATCH ")):
            runnable = True
    return text if runnable else None


_WEB_PAYLOAD = {
    "injection": "' OR '1'='1",
    "sql": "' OR '1'='1",
    "command_injection": "; id",
    "command": "; id",
    "path_traversal": "../../../../etc/passwd",
    "xss": "<script>alert(1)</script>",
    "ssrf": "http://169.254.169.254/latest/meta-data/",
    "authz": "<another-users-id>",
    "authn": "<forged-or-empty-credential>",
}


def _default_sketch(f: Finding) -> str:
    """Build a concrete, UNCOMMENTED reproduction sketch when no ``sample_request``
    could be resolved (e.g. the sink has no directly-attached route). States the
    method/endpoint/body/curl as best we can, with a `<BASE_URL>` placeholder and a
    note to adapt the route to the actual entry point that reaches this code."""
    loc = f"{f.file_rel}:{f.line_start}-{f.line_end}"
    cat = (f.category or "").lower()
    web = f.reachable == "reachable" and cat in (
        "injection", "sql", "command", "command_injection", "xss", "ssrf",
        "path_traversal", "authz", "authn")
    if web:
        payload = _WEB_PAYLOAD.get(cat, "<malicious-value>")
        return "\n".join([
            "- **Method:** GET or POST (match the entry point that reaches this code)",
            "- **Endpoint:** `<the route that invokes this handler>`",
            f"- **Payload:** `{payload}`  (for {cat} at `{loc}`)",
            "",
            "Adapt the route/param to the actual handler, then run against a target "
            "you own:",
            "",
            "```bash",
            f"curl -i '<BASE_URL>/<route-that-hits-this-code>' \\",
            # shlex.quote so payloads containing single quotes (the SQLi and
            # command-injection ones do) produce a command that actually runs.
            f"     --data {shlex.quote(f'input={payload}')}",
            "```",
            "",
            f"Observe the unsafe behavior described in the finding at `{loc}`.",
        ])
    if cat == "secrets":
        return "\n".join([
            f"Sensitive value referenced at `{loc}`.",
            "",
            "1. Confirm the value is a live/production credential (not a placeholder).",
            "2. Verify whether it is reachable/loaded at runtime vs. build-only.",
            "3. If live: rotate immediately and remove it from source history.",
        ])
    if cat == "csrf":
        # A CSRF PoC is not a curl with a payload — it is a page that makes the
        # VICTIM's browser send the request, riding their session.
        return "\n".join([
            f"Cross-site request forgery at `{loc}` — the state-changing route "
            "accepts requests with no anti-CSRF token / SameSite protection.",
            "",
            "1. Save an auto-submitting HTML form (or fetch) pointing at the route "
            "that reaches this code.",
            "2. Open it in a browser while logged in as a victim user.",
            "3. Observe the state change happening without the victim's intent.",
        ])
    return "\n".join([
        f"Reproduction for {f.title or cat} at `{loc}`:",
        "",
        "1. Identify the caller/entry point that exercises this code path.",
        "2. Supply the input/conditions described in the finding.",
        "3. Observe the unsafe behavior. Adapt to your environment.",
    ])
